#!/usr/bin/env php
<?php

declare(strict_types=1);

use App\Models\Calculator;

const BASE_DIR = __DIR__.'/';
require BASE_DIR.'vendor/autoload.php';

$calculator = new Calculator();
$calculator->run();