#!/usr/bin/env php
<?php

declare(strict_types=1);

use App\Models\Calculator;

const BASE_DIR = __DIR__.DIRECTORY_SEPARATOR;
require BASE_DIR.'vendor'.DIRECTORY_SEPARATOR.'autoload.php';

new Calculator(
    operators: ['+', '-', '*', '/',],
    mathFunctions: ['sqrt',]
)->run();